image: node:9.11

stages:
    - lint
    - test
    - build
    - package

# cache:
#     paths:
#         - node_modules

before_script:
    - echo "unsafe-perm=true" > ~/.npmrc
    - npm install

lint sources:
    stage: lint
    script:
        - npm run lint

test sources:
    stage: test
    script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
        - npm run test:ci
        - ./cc-test-reporter after-build --exit-code $?

build app:
    stage: build
    script:
        - npm run ng -- build --prod --progress=false

package linux app:
    stage: package
    artifacts:
        name: "$CI_COMMIT_REF_NAME"
        paths:
            - out/ngx-ssb-client-x86_64.AppImage
            - out/ngx-ssb-client-amd64.snap
    script:
        - npm run electron:linux
