test: off

artifacts:
  - path: out/ngx-ssb-client.exe
    name: Application (64 Bit)

build_script:
  ps: |
    npm --silent install
    npm run --silent electron:windows

# deploy_script:
#   - ps: |
#     if($env:appveyor_repo_tag -eq 'True') {
#         print hallo
#     }
