# branches:
#     only:
#         - master

test: off

build_script:
    ps: |
        npm --silent install
        npm run build:prod

environment:
    GITHUB_TOKEN:
        secure: c2eb22TX3Np2x1UhLnGp4IYhrf+QNzemudTOxzhoyyT6iT3Rp1lh0BHFBUlpl2Ji

deploy_script:
  - ps: >-
      Write-Host $env:APPVEYOR_REPO_TAG ;
      if($env:APPVEYOR_REPO_TAG -eq 'true') {
        npm run --silent electron:windows
      }
