test: off

artifacts:
  - path: dist/ngx-ssb-client Setup 0.1.0.exe
    name: Application

build_script:
  ps: |
    npm --silent install
    npm run --silent electron:windows

# deploy_script:
#   - ps: |
#     if($env:appveyor_repo_tag -eq 'True') {
#         print hallo
#     }
